Sprint 1/step 1
igoral5/react-burger pull request #1
Opened 2022-10-27 19:05 UTC by igoral5

Выполнен шаг 1 первого спринта.

2022-10-27 19:46 UTC, andryxxa93 requested changes
Хорошая работа! Код написан чисто и понятно. Понравилась декомпозиция компонентов. Есть пару замечаний - сейчас вы можете их не исправлять, но на финальном этапе сдачи работы они станут обязательными.

1. По макету в списке должны отображаться все ингредиенты.
Вот так должно выглядеть.
<img width="354" alt="Снимок экрана 2022-10-27 в 22 40 33" src="https://user-images.githubusercontent.com/60173362/198383154-5879d09e-3bf9-46e2-9f17-5fff26682ed6.png">
2. У элементов булок не должно быть иконок перемещения.
<img width="445" alt="Снимок экрана 2022-10-27 в 22 43 31" src="https://user-images.githubusercontent.com/60173362/198383763-25d25048-c418-43e5-9105-80cfbaa6539e.png">

Удачной работы!

2022-10-27 19:46 UTC, andryxxa93 commented on src/components/app-header/app-header.js
> +                </div>
**Необходимо исправить**
Элемент навигации должен быть ссылкой. Т.е. заключен в тег `<a>`.

2022-10-27 19:46 UTC, andryxxa93 commented on src/components/product-list/product-list.js
> +const ProductList = ({data, type}) => {
**Круто!**
Вы создали универсальный компонент чтобы не повторять верстку - это здорово.

2022-10-27 21:14 UTC, igoral5 commented on src/components/app-header/app-header.js
> +                </div>
Заменил на ссылку

2022-10-27 21:20 UTC, igoral5 commented
> 1. По макету в списке должны отображаться все ингредиенты.
>    Вот так должно выглядеть.
> 
> <img alt="Снимок экрана 2022-10-27 в 22 40 33" width="354" src="https://user-images.githubusercontent.com/60173362/198383154-5879d09e-3bf9-46e2-9f17-5fff26682ed6.png">

Я сначала посчитал что на вкладке Булки, должны быть только Булки. На вкладке Соусы - только Соусы и так далее. Сделал эту фильтрацию в зависимости от выбранной вкладки. Сейчас убрал её, на всех вкладках - полный набор ингредиентов. 
> 2. У элементов булок не должно быть иконок перемещения.
> <img alt="Снимок экрана 2022-10-27 в 22 43 31" width="445" src="https://user-images.githubusercontent.com/60173362/198383763-25d25048-c418-43e5-9105-80cfbaa6539e.png">

Удалил иконки перемещения.

2022-10-28 05:56 UTC, andryxxa93 requested changes
Всё хорошо, небольшое замечание по вертске - 
Отступы между хедером и списком ингредиентов должен быть больше. И конструктор должен начинаться на одной линии с элементами навигации списка. 
<img width="917" alt="Снимок экрана 2022-10-28 в 08 51 09" src="https://user-images.githubusercontent.com/60173362/198513241-51fd2a86-39a0-4e32-b49d-8e67355e53dc.png">
Вот как должно быть - 
<img width="774" alt="Снимок экрана 2022-10-28 в 08 54 34" src="https://user-images.githubusercontent.com/60173362/198513634-be180dcf-fd09-4f1f-9df1-09d2e5c0ed88.png">

Во всё остальном всё хорошо. Можете приступать к финальному этапу.
Удачной работы!

2023-04-02 09:01 UTC, andryxxa93 commented
Супер, вы отлично поработали. Только не везде указали `isRequired` для обязательных пропсов, например в `BurgerIngredients`. Должно быть так `data: dataArrayPropTypes.isRequired`. Во всём остальном всё отлично.
Работа принята, вы можете приступать к финальному этапу сдачи работы! Удачи!

2023-04-02 10:47 UTC, merged