Sprint 1/step 2
igoral5/react-burger pull request #2
Opened 2023-04-08 11:31 UTC by igoral5

2023-04-09 05:59 UTC, andryxxa93 requested changes
Проделана большая работа 👍 
Что понравилось:
- Есть отписка от слушателя событий
- Хороший `codestyle` - ничего лишнего

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавьте проверку успешности запроса
- У `ModalOverlay` не должно быть никакой логики и `children` - это просто подложка.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-09 05:59 UTC, andryxxa93 commented on src/components/main/main.js
> +                const resData = await res.json();
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-04-09 05:59 UTC, andryxxa93 commented on src/components/main/main.js
> +        const getIngredients = async () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-04-09 05:59 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +            <WithVisibleTotal value={2 * data[0].price + data.slice(1).reduce((acc, it) => acc + it.price, 0)} />
**Можно лучше**
В данном случае `WithVisibleTotal ` не даёт больших преимуществ, но усложняет функционал. Тут можно просто рендерить по условию `Total`. То же касается и использования с `Product`.

2023-04-09 14:33 UTC, igoral5 commented on src/components/burger-constructor/burger-constructor.js
> +            <WithVisibleTotal value={2 * data[0].price + data.slice(1).reduce((acc, it) => acc + it.price, 0)} />
Устранил указанные недостатки

2023-04-10 07:13 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-10 07:14 UTC, merged