Sprint 3/step 1
igoral5/react-burger pull request #5
Opened 2023-05-02 06:42 UTC by igoral5

2023-05-02 11:47 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали **отличную** работу по добавлению роутинга в ваш проект, есть удобные модалки, необходимые роуты защищены и аккуратно прописаны, добавлен оптимальный способ подсчёта счетчиков, вы молодец, **так держать** 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Формы в проекте следует обернуть в соответствующий тег `<form>` и отслеживать отправку данных по событию `onSubmit`;
- В заказе следует разместить две булки: одну в начале, а другую - в конце массива, как они расположены в конструкторе ингредиента;

Также, в рамках ревью были предложены **улучшения** вашего кода, которые могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, в том числе:

- Не рекомендуется сбрасывать данные в форме в случае неуспешного запроса, возможно пользователь ошибся немного, а данные необходимо будет заполнять заново полностью.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-05-02 11:47 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.js
> +    const counters = useMemo(() => {
🟢 **Отлично:**

Оптимальный подход по подсчёту счетчиков 👍 
В качестве улучшения можно рассмотреть вариант с изменением кол-ва конкретного ингредиента в момент его добавления или удаления из конструктора с хранением объекта счетчиков в редаксе

2023-05-02 11:47 UTC, randomroot commented on src/components/product-list/product-list.js
> +    counters: PropsTypes.object.isRequired
🟡 **Можно улучшить:**

Не рекомендуется использовать при описании `PropTypes.object`, т.к. он позволяет передать абсолютно любой объект, даже если он не соответствует внутренней логике компонента. Опишите ожидаемый объект через `PropTypes.shape`;

2023-05-02 11:47 UTC, randomroot commented on src/components/total/total.js
> +                postOrder(bun ? [bun._id, ...ingredientIds] : ingredientIds)
🔴 **Нужно исправить:**

В заказе следует разместить две булки: одну в начале, а другую - в конце массива, как они расположены в конструкторе ингредиента, чтобы осуществлялся корректный расчет стоимости (счетчик показывает ведь 2), а сборщики смогли собрать вкусный заказ :)

2023-05-02 14:21 UTC, igoral5 commented on src/components/burger-ingredients/burger-ingredients.js
> +    const counters = useMemo(() => {
В случае хранения объекта счетчиков в Redux возникает потенциальная возможность расхождения объекта счетчиков и состава бургера. Кроме того дублируется код связанный с добавлением булок. Решил оставить динамический способ получения counters.

2023-05-02 14:25 UTC, igoral5 commented on src/components/product-list/product-list.js
> +    counters: PropsTypes.object.isRequired
Объект counters является динамическим и в нем нельзя указать его shape, поэтому лучшее что я смогу здесь сделать: counters: PropsTypes.objectOf(PropsTypes.number).isRequired т.к. мы храним количество  - сколько раз продукт с данным id использован в бургере.

2023-05-02 14:25 UTC, igoral5 commented on src/components/total/total.js
> +                postOrder(bun ? [bun._id, ...ingredientIds] : ingredientIds)
Сделано

2023-05-03 05:37 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-05-03 06:15 UTC, merged