Sprint 6/step 1
igoral5/react-burger pull request #8
Opened 2023-06-22 13:39 UTC by igoral5

2023-06-22 15:18 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Все юнит-тесты (48 шт) проходят успешно
- Все Cypress тесты проходят успешно
- В readme есть ссылка на проект.

### **Есть 1 маленькое замечание, которое нужно исправить:**

- url адрес нужно вынести в константу и переиспользовать.

  <https://docs.cypress.io/guides/references/configuration#Intelligent-Code-Completion>n

### **Сделает код лучше:**

- Чтобы проверить процент покрытия тестами всех файлов, используйте команду `react-scripts test --coverage --watchAll`

2023-06-22 15:18 UTC, ArslanMustafin commented on cypress/e2e/constructor.cy.js
> +        cy.visit('http://localhost:3000/login')
**Надо исправить:**

url адрес нужно вынести в константу и переиспользовать.

https://docs.cypress.io/guides/references/configuration#Intelligent-Code-Completion

2023-06-22 15:18 UTC, ArslanMustafin commented on src/services/reducers/ingregients.test.js
> +    mapping: {},
**Можно лучше:**

вместо `{}` лучше использовать `null`.

2023-06-22 16:30 UTC, igoral5 commented on cypress/e2e/constructor.cy.js
> +        cy.visit('http://localhost:3000/login')
Добавил в конфигурацию cypress параметр baseUrl: 'http://localhost:3000'

2023-06-22 16:30 UTC, igoral5 commented on src/services/reducers/ingregients.test.js
> +    mapping: {},
Изменил mapping: {} to mapping: null

2023-06-23 07:20 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.🔥

### **Вы молодец! Работа принята.**

- Все замечания были исправлены.

Несколько советов для дальнейшего развития:

- Сверстайте несколько небольших проектов для себя, для закрепления знаний, и чтобы можно добавить их в портфолио.

- Ходите на собеседования: опыт прохождения собеседований не менее важен знаний теории, и Вы поймете, какие знания требуются на рынке, и где Вы проседаете.

- Читайте habr и слушаете подкаксты: они очень хорошо расширяют кругозор и позволяют узнать, что происходит в отрасли.

2023-06-23 07:23 UTC, merged